---
reference: hg38
manifest: manifest.tab

barcode_fasta: /path/to/barcode.fa
barcode_prefix: s_1_

mrsfast_path: /net/eichler/vol6/software/modules-sw/mrsfast/3.3.8/Linux/RHEL6/x86_64/mrsfast/mrsfast
mrsfast_opts: "--outcomp -n 0 -e 2 --crop 36"

track_output_dir: ~/public_html/tracks
track_url: genometest2.gs.washington.edu/~`whoami`/tracks

hg38:
    sunk_mask: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/hg38_sunk_mask_track_pad36_e0.dts
    sunk_bed: /net/eichler/vol2/eee_shared/assemblies/hg38/sunks/hg38_sunks.bed
    mrsfast_index: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/mrsfastULTRA/hg38.rmsk_and_trf.fa
    contigs: /net/eichler/vol2/eee_shared/assemblies/hg38/ucsc.hg38.fasta.fai
    cores: /net/eichler/vol2/eee_shared/assemblies/hg38/cores/pseudocores.bed
